### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by jpata** [hepaccelerate/hepaccelerate#8]
via @matthewfeickert on my now-private fork https://github.com/jpata/hepaccelerate/issues/4

> Hi @jpata. Thanks for the [very nice talk at PyHEP today](https://indico.cern.ch/event/833895/contributions/3577804/) where I learned about `hepaccelerate`. Looking at `hepaccelerate` I see that it isn't on PyPI and that you recommend that the user install from GitHub
> 
> > pip install git+https://github.com/jpata/hepaccelerate@v0.1.0
> 
> Though this is a bit strange as you have an upload command in `setup.py`
> 
> https://github.com/jpata/hepaccelerate/blob/f1fc126672b4ce94ae080821d28d916bea2c8714/setup.py#L58-L86
> 
> Is there a specific reason it is not on PyPI? If no, would you consider publishing it there?

**Comment by jpata** [comment]
Now published on PyPI: https://pypi.org/project/hepaccelerate/

@matthewfeickert if you have a moment, I would appreciate your scrutiny & advice how the packaging could be improved.

**Comment by jpata** [comment]
Closing this now, in case there is any problem with `pip install`, can follow up in a new issue :)

**Comment by matthewfeickert** [comment]
> Now published on PyPI: https://pypi.org/project/hepaccelerate/
> 
> @matthewfeickert if you have a moment, I would appreciate your scrutiny & advice how the packaging could be improved.

Sorry, I've been a bit busy and sick this last week. If you were able to get things up on PyPI without much trouble that's great and I think you're good to go. Though if you want I can still take a look over your `setup.py` and open up a PR of suggestions (though it is going to be mostly on what is the current somewhat trendy recommendations of the PyPA). I myself am still working on getting a system setup for automated builds and deployments to PyPI using CI and release tags.

**Comment by jpata** [comment]
Thanks @matthewfeickert and no worries! If you have a chance to take a look at the `setup.py` and suggest how to better follow python packaging best practices, I certainly would appreciate, but don't worry too much about it!
